### ISSUE TITLE
[1.18.2] OK Zoomer + Vanilla Hammers + Trinkets = No More Trinket Slots

### ISSUE THREAD

**Issue by BeardedThorgi** [joaoh1/OkZoomer#71]
When installing OK Zoomer and Vanilla Hammers (a tool mod that adds hammers) together, all of the trinket slots from the 'Trinkets' mod disappear. Neither of these mods interact with trinkets, Vanilla Hammers just adds new tools. I've tested pretty thoroughly and tried with only OK Zoomer, Vanilla Hammers, Trinkets, Fabric API, and two different mods that work with Trinkets (INMIS and Cosmetic Armor; tried combinations of either and both, in case they were conflicting). If I remove either OK Zoomer or Vanilla Hammers, all of the trinket slots begin working; it only conflicts with both installed.

Note that the issue does NOT occur on the small server I host. I believe because OK Zoomer is a client-side mod and Vanilla Hammers has to be on both server and client, OK Zoomer conflicts with whatever part of Vanilla Hammers is loaded on a server when playing in a single-player world. Thanks for your help!

**Comment by EnnuiL** [comment]
This dependency snarl should be fixed by Ok Zoomer 5.0.0-beta.7 (which migrates it to Quilt); If not, please reopen this issue

**Comment by BeardedThorgi** [comment]
I'm staying with Fabric for the time being as Quilt is very problematic across several Fabric mods, so the issue isn't resolved on Fabric. If you're abandoning the Fabric version I'll just switch Zoom mods. Thanks.
